# Generated by Django 5.2.4 on 2025-08-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='can_cancel',
            field=models.BooleanField(default=True),
        ),
    ]
