# Generated by Django 5.2.4 on 2025-09-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_booking_can_cancel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("vehicle_number", models.CharField(max_length=20)),
                ("rating", models.FloatField(default=4.5)),
                ("photo_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="vehicle_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.driver",
            ),
        ),
    ]
